version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: lifebet
workflows:
  version: 2
  build_and_test:
    jobs:
      - build