version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: lifebet
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .
  unittest:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Unit Test
          command: dotnet test --no-build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unittest:
          requires:
            - build